- name: Create Azure VM
  hosts: localhost
  connection: local
  vars_files:
    - /vars/variables.yml
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: {{ resource_group }}
      location: {{ resource_group_location }}
    register: resource_group

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: {{ resource_group }}
      name: {{ vnet_name }}
      address_prefixes: {{ vnet_address_prefixes }}
    register: virtual_network 

  - name: Add subnet to the virtual network
    azure_rm_subnet:
      resource_group: {{ resource_group }}
      name: {{ subnet_name }}
      address_prefix: {{ subnet_address_prefixes }}
      virtual_network: {{ vnet_name }}
    register: subnet_network

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: {{ resource_group }}
      allocation_method: Static
      name: {{ network_vm_public_ip }}
    register: output_ip_address

  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP of your VM is {{ output_ip_address.state.ip_address }}."
      
  - name: Create Network Security Group that allows SSH from your provider public IP 
    azure_rm_securitygroup:
      resource_group: {{ resource_group }}
      name: {{ network_security_group_name }}
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          source_port_range: *
          access: Allow
          priority: 1001
          direction: Inbound
          source_address_prefix: {{ network_provider_public_ip }}
          destination_address_prefix: {{ subnet_address_prefixes }}
          description: "Allow from MY ISP IP"
 
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: {{ resource_group }}
      name: {{ vm_nic_name }}
      virtual_network: {{ vnet_name }}
      subnet: {{ subnet_name }}
      public_ip_name: {{ network_vm_public_ip_name }}
      security_group: {{ network_security_group_name }}
    register: nic_card 

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: {{ resource_group }}
      name: {{ vm_name }}
      tags: {{ vm_tags }}
      vm_size: {{ vm_size }}
      admin_username: {{ vm_admin_username }}
      short_hostname: {{ vm_ hostname}}
      ssh_password_enabled: false
      ssh_public_keys:
        - path: {{ ssh_keys_path_dest }}
          key_data: {{ public_ssh_key }}
      network_interfaces: {{ vm_nic_name }}      
      image:
        offer: {{ vm_offer }}
        publisher: {{ vm_publisher }}
        sku: {{ vm_sku }}
        version: {{ vm_version }}
      data_disks:
        - lun: 0
          disk_size_gb: {{ vm_disk_size }}
          managed_disk_type: {{ vm_disk_managed_type }} 
          storage_container_name: {{ vm_disk_storage_container_name }}
    register: vm01