---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - vim
      - software-properties-common
    state: present

- name: Add Kubernetes GPG apt key.
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  register: add_repository_key
  ignore_errors: "{{ kubernetes_apt_ignore_key_error }}"

- name: Add Docker GPG apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  register: add_repository_key_docker
  ignore_errors: "{{ kubernetes_apt_ignore_key_error }}"

- name: Add Kubernetes repository.
  apt_repository:
    repo: "{{ kubernetes_apt_repository }}"
    state: present
    update_cache: true

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present

- name: Add Kubernetes apt preferences file to pin a version.
  template:
    src: ../templates/apt-preferences-kubernetes.j2
    dest: /etc/apt/preferences.d/kubernetes
