- name: Creating AKS CNI
  hosts: localhost
  connection: local
  vars_files:
    - vars/variables.yml
  tasks:
  - name: Ensure resource group exists
    azure_rm_resourcegroup:
      name: "{{ appgtw_resource_group }}"
      location: "{{ resource_group_location }}"

  - name: Create vnet
    include_tasks: vnet.yml 

  - name: Create AKS
    include_tasks: aks.yml

  - name: Show AKS cluster detail
    debug:
      var: aks

  - name: Get Kubeconfig for one Azure Kubernetes Service
    azure_rm_aks_info:
      name: "{{ aks_cluster_name }}"
      resource_group: "{{ aks_resource_group }}"
      show_kubeconfig: user
        
  - name: Create VM 
    include_tasks: vm.yml

  - name: AKS Ingress Configuration       
    include_tasks: ing.yml

