- name: AKS-Management
  hosts: localhost
  connection: local
  vars_files:
    - vars/variables.yml
  tasks: 
  - name: Get Kubeconfig for one Azure Kubernetes Service
    azure_rm_aks_info:
      name: "{{ aks_cluster_name }}"
      resource_group: "{{ aks_resource_group }}"
      show_kubeconfig: user
  - 
